<?php
namespace wcf\system\steam;
use wcf\system\exception\SteamException;
use wcf\system\exception\SystemException;
use wcf\util\exception\HTTPException;
use wcf\util\HTTPRequest;
use wcf\util\JSON;

/**
 * Steam Web Api class
 * api key can got from here: https://steamcommunity.com/dev/apikey
 * method documentation is from original documentations
 * 
 * @see https://steamcommunity.com/dev
 * @see https://openid.net/specs/openid-authentication-2_0.html
 * @see https://wiki.teamfortress.com/wiki/WebAPI
 * @see https://partner.steamgames.com/doc/webapi
 * @see https://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1/
 * 
 * @author Peter Lohse <hanashi@hanashi.eu>
 * @copyright Hanashi Development
 * @license	Freie Lizenz (https://hanashi.dev/freie-lizenz/)
 * @package	WoltLabSuite\Core\System\Steam
 */
class SteamAPI {
	/**
	 * base api of steam
	 * 
	 * @var string
	 */
	protected $apiURL = 'http://api.steampowered.com/';

	/**
	 * request uri, generated by construct
	 * 
	 * @var string
	 */
	protected $requestUri;


	/**
	 * data of request
	 * 
	 * @var array
	 */
	protected $data;

	/**
	 * construct of SteamAPI class
	 */
	public function __construct(string $interface, string $method, string $version, array $data) {
		$this->requestUri = $this->apiURL . $interface . '/' . $method . '/v' . $version . '/';
		$this->data = $data;
	}

	/********************* ISteamApps *********************/

	/**
	 * Full list of every publicly facing program in the store/library
	 * 
	 * @return 	list of every publicly facing program in the store/library
	 */
	public static function getAppList() : array {
		$data = [
			'format' => 'json'
		];

		$steam = new SteamAPI('ISteamApps', 'GetAppList', '2', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['applist']['apps'])) throw new SteamException('Unknown Steam API exception');

		return $reply['applist']['apps'];
	}

	/**
	 * Shows all steam-compatible servers related to a IPv4 Address
	 * 
	 * @var		string	$addr	IP Address of Server (IPv4 format)
	 * @return	array	game server status
	 */
	public static function getServersAtAddress(string $addr) : array {
		$data = [
			'format' => 'json',
			'addr' => $addr
		];

		$steam = new SteamAPI('ISteamApps', 'GetServersAtAddress', '1', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['response'])) throw new SteamException('Unknown Steam API exception');

		return $reply['response'];
	}

	/**
	 * Check if a given app version is the most current available
	 * 
	 * @var		int		$appID		AppID of game
	 * @var		int		$version	The installed version of the game
	 * @return	array	status of game version
	 */
	public static function upToDateCheck(int $appID, int $version) : array {
		$data = [
			'format' => 'json',
			'appid' => $appID,
			'version' => $version
		];

		$steam = new SteamAPI('ISteamApps', 'UpToDateCheck', '1', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['response'])) throw new SteamException('Unknown Steam API exception');

		return $reply['response'];
	}

	/********************* ISteamEconomy *********************/
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetAssetClassInfo

	/**
	 * Prices of items in the economy
	 * 
	 * @var		int		$appID		The ID of the game to query assets from.
	 * @var		string	$currency	(optional) The ISO 4217 code for currency specific filtering.
	 * @var		string	$language	(optional) The ISO639-1 language code for the language all localized strings should be returned in. Not all strings have been translated to every language. If a language does not have a string, the English string will be returned instead. If this parameter is omitted the string token will be returned for the strings.
	 * @return 	array	
	 */
	public static function getAssetPrices(int $appID, string $currency = null, string $language = null) : array {
		$data = [
			'format' => 'json',
			'appid' => $appID
		];
		if (!empty($currency)) {
			$data['currency'] = $currency;
		}
		if (!empty($language)) {
			$data['language'] = $language;
		}

		$steam = new SteamAPI('ISteamEconomy', 'GetAssetPrices', '0001', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['result'])) throw new SteamException('Unknown Steam App ID');

		return $reply['result'];
	}

	/********************* ISteamEconomy *********************/

	/**
	 * returns the latest news of a game specified by its appID
	 * 
	 * @var 	int		$appID		AppID of the game you want the news of.
	 * @var 	int		$count 		(optional) How many news enties you want to get returned.
	 * @var 	int		$maxLength	(optional) Maximum length of each news entry.
	 * @return 	array	latest news of a game
	 */
	public static function getNewsForApp(int $appID, int $count = null, int $maxLength = null) : array {
		$data = [
			'format' => 'json',
			'appid' => $appID
		];
		if (!empty($count)) {
			$data['count'] = $count;
		}
		if (!empty($maxLength)) {
			$data['maxlength'] = $maxLength;
		}

		$steam = new SteamAPI('ISteamNews', 'GetNewsForApp', '0002', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['appnews'])) throw new SteamException('Unknown App ID');

		return $reply['appnews'];
	}

	/********************* ISteamRemoteStorage *********************/
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetCollectionDetails
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetPublishedFileDetails
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetUGCFileDetails

	/********************* ISteamUser *********************/

	/**
	 * returns the friend list of any Steam user, provided their Steam Community profile visibility is set to "Public"
	 * 
	 * @var		int		$steamID		64 bit Steam ID to return friend list for
	 * @var		string	$relationShip	Relationship filter. Possibles values: all, friend
	 * @return	array	friend list of any Steam user, provided their Steam Community profile visibility is set to "Public"
	 */
	public static function getFriendList(int $steamID, string $relationShip = 'friend') : array {
		$data = [
			'format' => 'json',
			'steamid' => $steamID,
			'relationship' => $relationShip
		];

		$steam = new SteamAPI('ISteamUser', 'GetFriendList', '0001', $data);
		$reply = $steam->execute();
		if (!is_array($reply)) throw new SteamException('Unknown Steam ID');

		return $reply;
	}

	/**
	 * returns Community, VAC, and Economy ban statuses for given players.
	 * 
	 * @var		array		list of SteamIDs
	 * @return	array		Community, VAC, and Economy ban statuses for given players
	 */
	public static function getPlayerBans(array $steamIDs) : array {
		$data = [
			'format' => 'json',
			'steamids' => implode(',', $steamIDs)
		];

		$steam = new SteamAPI('ISteamUser', 'GetPlayerBans', '1', $data);
		$reply = $steam->execute();
		if (!isset($reply['players'])) throw new SteamException('Unknown Steam API exception');

		return $reply['players'];
	}

	/**
	 * returns basic profile information for a list of 64-bit Steam IDs
	 * 
	 * @var		array	$steamIDs	List of 64 bit Steam IDs to return profile information for. Up to 100 Steam IDs can be requested.
	 * @return	array	basic profile information for a list of 64-bit Steam IDs (Some data associated with a Steam account may be hidden if the user has their profile visibility set to "Friends Only" or "Private". In that case, only public data will be returned.)
	 */
	public static function getPlayerSummaries(array $steamIDs) : array {
		$data = [
			'format' => 'json',
			'steamids' => implode(',', $steamIDs)
		];

		$steam = new SteamAPI('ISteamUser', 'GetPlayerSummaries', '0002', $data);
		$reply = $steam->execute();
		if (!isset($reply['response'])) throw new SteamException('Unknown Steam IDs');

		return $reply['response'];
	}

	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetUserGroupList
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/ResolveVanityURL

	/********************* ISteamUser *********************/

	/**
	 * returns global achievements overview of a specific game in percentages
	 * 
	 * @var		int		$appID		AppID of the game you want the percentages of.
	 * @return	array	global achievements overview of a specific game in percentages
	 */
	public static function getGlobalAchievmentPercentagesForApp(int $appID) : array {
		$data = [
			'format' => 'json',
			'gameid' => $appID
		];

		$steam = new SteamAPI('ISteamUserStats', 'GetGlobalAchievementPercentagesForApp', '0002', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['achievementpercentages'])) throw new SteamException('Unknown App ID');

		return $reply['achievementpercentages'];
	}

	/**
	 * returns global stats of a specific game
	 * 
	 * @var		int		$appID		AppID of the game you want the stats of
	 * @var		array	$names		Name of the achievement as defined in Steamworks. (name[0] [and name[1], etc.])
	 * @var		int		$count		Length of the array of global stat names you will be passing.
	 * @return	array	global stats of a specific game
	 */
	public static function getGlobalStatsForGame(int $appID, array $names, int $count = 1) : array {
		$data = [
			'format' => 'json',
			'appid' => $appID
		];
		for ($i = 0; $i < count($names); $i++) {
			$data['name['.$i.']'] = $names[$i];
		}
		if (!empty($count)) {
			$data['count'] = $count;
		}

		$steam = new SteamAPI('ISteamUserStats', 'GetGlobalStatsForGame', '0001', $data);
		$reply = $steam->execute(false);
		if (!isset($reply['response'])) throw new SteamException('Unknown App ID');

		return $reply['response'];
	}

	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetNumberOfCurrentPlayers

	/**
	 * returns a list of achievements for this user by app id
	 * 
	 * @var		int		$steamID		64 bit Steam ID to return achievements for.
	 * @var		int		$appID			The ID for the game you're requesting
	 * @var		string	$language		(optional) Language. If specified, it will return language data for the requested language.
	 * @return	array	list of achievements for this user by app id
	 */
	public static function getPlayerAchievments(int $steamID, int $appID, string $language = null) : array {
		$data = [
			'format' => 'json',
			'steamid' => $steamID,
			'appid' => $appID
		];
		if (!empty($language)) {
			$data['l'] = $language;
		}

		$steam = new SteamAPI('ISteamUserStats', 'GetPlayerAchievements', '0001', $data);
		$reply = $steam->execute();
		if (!is_array($reply)) throw new SteamException('Unknown Steam ID');

		return $reply;
	}

	/**
	 * returns gamename, gameversion and availablegamestats (achievements and stats).
	 * 
	 * @var		int			$appID		The AppID of the game you want stats of
	 * @var		string		$language	(optional) Language. If specified, it will return language data for the requested language.
	 * @return	array		gamename, gameversion and availablegamestats (achievements and stats).
	 */
	public static function getSchemaForGame(int $appID, string $language = null) : array {
		$data = [
			'format' => 'json',
			'appid' => $appID
		];
		if (!empty($language)) {
			$data['l'] = $language;
		}

		$steam = new SteamAPI('ISteamUserStats', 'GetSchemaForGame', '0002', $data);
		$reply = $steam->execute();
		if (!isset($reply['game'])) throw new SteamException('Unknown Steam ID');

		return $reply['game'];
	}

	/**
	 * returns a list of stats for this user by app id
	 * 
	 * @var		int		$steamID		64 bit Steam ID to return stats for.
	 * @var		int		$appID			The ID for the game you're requesting
	 * @var		string	$language		(optional) Language. If specified, it will return language data for the requested language.
	 * @return	array	list of stats for this user by app id
	 */
	public static function getUserStatsForGame(int $steamID, int $appID, string $language = null) : array {
		$data = [
			'format' => 'json',
			'steamid' => $steamID,
			'appid' => $appID
		];
		if (!empty($language)) {
			$data['l'] = $language;
		}

		$steam = new SteamAPI('ISteamUserStats', 'GetUserStatsForGame', '0002', $data);
		$reply = $steam->execute();
		if (!is_array($reply)) throw new SteamException('Unknown Steam ID');

		return $reply;
	}

	/********************* IPlayerService *********************/

	/**
	 * returns a list of games a player has played in the last two weeks, if the profile is publicly visible. Private, friends-only, and other privacy settings are not supported unless you are asking for your own personal details (ie the WebAPI key you are using is linked to the steamid you are requesting).
	 * 
	 * @var		int		$steamID	The SteamID of the account.
	 * @var		int		$count		(optional) Optionally limit to a certain number of games (the number of games a person has played in the last 2 weeks is typically very small)
	 * @return	array	list of games a player has played in the last two weeks
	 */
	public static function getRecentlyPlayedGames(int $steamID, int $count = null) : array {
		$data = [
			'format' => 'json',
			'steamid' => $steamID
		];
		if (!empty($count)) {
			$data['count'] = $count;
		}

		$steam = new SteamAPI('IPlayerService', 'GetRecentlyPlayedGames', '0001', $data);
		$reply = $steam->execute();
		if (!isset($reply['response'])) throw new SteamException('Unknown Steam ID');

		return $reply['response'];
	}

	/**
	 * returns a list of games a player owns along with some playtime information, if the profile is publicly visible. Private, friends-only, and other privacy settings are not supported unless you are asking for your own personal details (ie the WebAPI key you are using is linked to the steamid you are requesting).
	 * 
	 * @var		int		$steamID			The SteamID of the account.
	 * @var		bool	$includeAppInfo		(optional) Include game name and logo information in the output. The default is to return appids only.
	 * @var		bool	$includeFreeGames	(optional) By default, free games like Team Fortress 2 are excluded (as technically everyone owns them). If include_played_free_games is set, they will be returned if the player has played them at some point. This is the same behavior as the games list on the Steam Community.
	 * @var		array	$appIDs				(optional) You can optionally filter the list to a set of appids.
	 * @return	array	list of games a player owns along with some playtime information
	 */
	public static function getOwnedGames(int $steamID, bool $includeAppInfo = true, bool $includeFreeGames = false, array $appIDs = []) : array {
		$inputJson = [
			'steamid' => $steamID
		];
		if ($includeAppInfo) {
			$inputJson['include_appinfo'] = 'true';
		} else {
			$inputJson['include_appinfo'] = 'false';
		}
		if ($includeFreeGames) {
			$inputJson['include_played_free_games'] = 'true';
		} else {
			$inputJson['include_played_free_games'] = 'false';
		}
		if (count($appIDs)) {
			$inputJson['appids_filter'] = $appIDs;
		}

		$data = [
			'format' => 'json',
			'input_json' => JSON::encode($inputJson)
		];

		$steam = new SteamAPI('IPlayerService', 'GetOwnedGames', '0001', $data);
		$reply = $steam->execute();
		if (!isset($reply['response'])) throw new SteamException('Unknown Steam ID');
		
		return $reply['response'];
	}

	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetSteamLevel
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetBadges
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetCommunityBadgeProgress

	/**
	 * returns the original owner's SteamID if a borrowing account is currently playing this game. If the game is not borrowed or the borrower currently doesn't play this game, the result is always 0.
	 * 
	 * @var		int		$steamID		The SteamID of the account playing.
	 * @var		int		$appIDPlaying	The AppID of the game currently playing
	 * @return	int		original owner's SteamID if a borrowing account is currently playing this game
	 */
	public static function isPlayingSharedGame(int $steamID, int $appIDPlaying) : int {
		$data = [
			'format' => 'json',
			'steamid' => $steamID,
			'appid_playing' => $appIDPlaying
		];

		$steam = new SteamAPI('IPlayerService', 'IsPlayingSharedGame', '0001', $data);
		$reply = $steam->execute();
		if (!isset($reply['response']['lender_steamid'])) throw new SteamException('Unknown Steam ID');

		return $reply['response']['lender_steamid'];
	}

	/********************* ISteamWebAPIUtil *********************/

	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetServerInfo
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetSupportedAPIList

	/********************* ISteamWebAPIUtil *********************/

	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetPlayerItems
	// TODO: https://wiki.teamfortress.com/wiki/WebAPI/GetSchema

	// TODO: Game specific interfaces

	/********************* OpenID *********************/

	/**
	 * get OpenID login url
	 * 
	 * @var 	string	$redirectUri	URL to which the OP SHOULD return the User-Agent with the response indicating the status of the request.
	 * @var 	string	$realm			URL pattern the OP SHOULD ask the end user to trust.
	 * @return 	string
	 */
	public static function getOpenIDUrl(string $redirectUri, string $realm) : string {
		$data = [
			'openid.ns' => 'http://specs.openid.net/auth/2.0',
			'openid.mode' => 'checkid_setup',
			'openid.return_to' => $redirectUri,
			'openid.realm' => $realm,
			'openid.claimed_id' => 'http://specs.openid.net/auth/2.0/identifier_select',
			'openid.identity' => 'http://specs.openid.net/auth/2.0/identifier_select'
		];
		return 'https://steamcommunity.com/openid/login?' . http_build_query($data, null, '&');
	}

	/**
	 * validate OpenID data and returns SteamID
	 * 
	 * @var		array	$data	content of $_GET by redirect uri, where prefix is "openid."
	 * @return	int		64 bit of SteamID
	 */
	public static function validateOpenID(array $data) : int {
		// TODO: implement
	}

	// TODO: vergleichen mit https://wiki.teamfortress.com/wiki/WebAPI
	// TODO: sort api functions

	public function execute($url = null, $data = [], bool $apiKeyImportant = true, bool $blankReturn = false) {
		if (empty($url)) $url = $this->requestUri;
		if (!count($data)) $data = $this->data;

		if ($apiKeyImportant && !STEAM_API_KEY)  throw new SteamException('Steam API key not configured.');

		if ($apiKeyImportant) {
			$data['key'] = STEAM_API_KEY;
		}
		$url = $url . '?' . http_build_query($data, null, '&');

		$request = new HTTPRequest($url);
		try {
			$request->execute();
			$reply = $request->getReply();
			if ($blankReturn) {
				return $reply['body'];
			} else {
				try {
					return JSON::decode($reply['body'], true);
				} catch (SystemException $e) {
					return $reply['body'];
				}
			}
		} catch (HTTPException $e) {
			throw new SteamException('Wrong Steam API call or Steam API is not reachable.');
		} catch (SystemException $e) {
			$reply = $request->getReply();
			if ($blankReturn) {
				return $reply['body'];
			} else {
				try {
					return JSON::decode($reply['body'], true);
				} catch (SystemException $e) {
					return $reply['body'];
				}
			}
		}
	}
}
