name: PHP

on:
  push:
  pull_request:

jobs:
  syntax:
    name: "Check Syntax (${{ matrix.php }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
        - '8.1'
        - '8.2'
    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - uses: actions/checkout@v4.0.0
    - run: echo "::add-matcher::.github/php-syntax.json"
    - run: |
        ! find . -type f -name '*.php' -exec php -l '{}' \; 2>&1 |grep -v '^No syntax errors detected'
